services:
  app:
    container_name: dokiv-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/stacks:/opt/stacks
      - .docker/data:/app/data
    environment:
      - STACKS_DIR=/opt/stacks
